### ISSUE TITLE
broken link to "Contribution guidelines"

### ISSUE THREAD

**Issue by vzx7** [ApeSwapFinance/apeswap-uikit#25]
Hi guys, I want to take part ...
But I can't take the first step.

apeswap-uikit/CONTRIBUTING.md
"Thanks for taking the time to contribute ! You can start by reading our **Contribution guidelines** first."

Broken link to "Contribution guidelines"...

Where can I read the rules?

**Comment by DeFiFoFum** [comment]
@vzx7 Thank you very much for subbmitting this issue. The Contribution guideline has been updated in this repo: https://github.com/ApeSwapFinance/apeswap-uikit/blob/main/CONTRIBUTING.md

Please let us know if you have any further problems. Happy Building! ❤️️
